plugin:
    name: 'mattlindesay.messaging::lang.plugin.name'
    description: 'User messaging system'
    author: 'Matt Lindesay'
    icon: oc-icon-paper-plane
    homepage: 'http://github.com/mattlindesay/messaging-plugin'
navigation:
    main-menu-item:
        label: 'mattlindesay.messaging::lang.plugin.name'
        url: /messaging
        icon: icon-paper-plane
        sideMenu:
            side-menu-item:
                label: Messages
                url: /messages
                icon: icon-paper-plane-o
