name: Messages
form: $/lindesay/messaging/models/message/fields.yaml
modelClass: Lindesay\Messaging\Models\Message
defaultRedirect: lindesay/messaging/messages
create:
    redirect: 'lindesay/messaging/messages/update/:id'
    redirectClose: lindesay/messaging/messages
update:
    redirect: lindesay/messaging/messages
    redirectClose: lindesay/messaging/messages
