name: Messages
form: $/mattlindesay/messaging/models/message/fields.yaml
modelClass: MattLindesay\Messaging\Models\Message
defaultRedirect: mattlindesay/messaging/messages
create:
    redirect: 'mattlindesay/messaging/messages/update/:id'
    redirectClose: mattlindesay/messaging/messages
update:
    redirect: mattlindesay/messaging/messages
    redirectClose: mattlindesay/messaging/messages
